name: GamesBuildAndRelease
on:
  push:
    branches: [ Builds ]

  workflow_dispatch:
    # inputs:
    #   Asteroids: Meteor Mayhem

jobs:
  build:
    strategy:
        matrix:
          versions: [ win-x64 ] #,'win-x86','win-arm','win-arm64', 'linux-x64', 'linux-musl-x64', 'linux-arm', 'linux-arm64', 'osx-x64']
          projects: [Asteroids]
          # include:
          #   - projects: Asteroids
          #     outputName: Meteor Mayhem  # assembly name as defined in .csproj
          #   - projects: ShittySnake
          #     outputName: Shitty Snake # assembly name as defined in .csproj
              
          
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:        
          dotnet-version: '6.0.x'
          include-prerelease: true
      - run: dotnet publish source/${{matrix.projects}}/${{matrix.projects}}.csproj -p:PublishSingleFile=true -c Release -r ${{matrix.versions}} -o 'out/{{ $inputs[${{matrix.projects}}]}} ${{matrix.versions}}'
      - run: Get-ChildItem '.\out\{{ $inputs[${{matrix.projects}}]}} ${{matrix.versions}}\' | Rename-Item -NewName { $_.Name -replace {{ $inputs[${{matrix.projects}}]}}, '{{ $inputs[${{matrix.projects}}]}}-${{matrix.versions}}'} 
      - uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: true
          tag: Games
          artifacts: "out/{{ $inputs[${{matrix.projects}}]}} ${{matrix.versions}}/*"
          commit: "Builds"
          token: ${{ secrets.GITHUB_TOKEN }}

